author = SingleDigitIQ
name = cozylights
description = voxel light maps
title = Cozy Lights
supported_games = *, minetest_game, mineclone2, mineclonia, voxelforge, regulus_mtgamejam_2023, mesecraft, tutorial, asuna, hades_revisited,
